[package]
name = "snp_reporter"
version = "0.1.0"
authors = ["Arron Norwell <anorwell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
